### ISSUE TITLE
gapless and ragtag or not to ragtag

### ISSUE THREAD

**Issue by splaisan** [schmeing/gapless#2]
Dear Devs and Users,

Using HiFi PacBio reads at high coverage depth (>300x), I am evaluating gapless as well as [ragtag](https://github.com/malonge/RagTag), the later having the nice extra feature of reference splitting and scaffolding contigs into pseudochromosomes.

Is there any reason **not to** denovo assemble (I am evaluating several assemblers here), followed by **pilon** polishing (some say do not with HiFi!), then **gapless**, and finally **ragtag**?

I would of course like to reduce the risk of over-fitting the sequences with all these polishing steps.

Any feedback is very welcome

Note: I am aiming at a haploid consensus assembly, not yet at haplotypes (although I get them with these tools but they may be overpolished!).

**Comment by schmeing** [comment]
Hi,

I am not sure gapless can improve a genome that was de novo assembled with the same data. Flye for example uses the variation in the data to separate repeat copies, which is not implemented in gapless so far.

Since you are planning to use ragtag with a reference in the end, you could try gapless to correct your reference with the reads.
